services:
  app:
    container_name: go-app
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/app
    tty: true
  db:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data:/var/lib/mysql
      