services:
  golang:
    container_name: golang
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/docker_test
    tty: true
  db:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql-data:/var/lib/mysql
      